BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS Users (
	UserID	TEXT NOT NULL UNIQUE,
	Username	TEXT NOT NULL,
	DisplayName	TEXT,
	PRIMARY KEY(UserID)
);
CREATE TABLE IF NOT EXISTS UserReacts (
	UserID	TEXT NOT NULL,
	TeamID	TEXT NOT NULL,
	ReactName	TEXT NOT NULL,
	Count	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(UserID,ReactName)
);
CREATE TABLE IF NOT EXISTS Messages (
	MessageID	TEXT NOT NULL,
	TeamID	TEXT NOT NULL,
	UserID	TEXT NOT NULL,
	MessageText	TEXT NOT NULL,
	PRIMARY KEY(MessageID)
);
CREATE TABLE IF NOT EXISTS MessageReacts (
	MessageID	TEXT NOT NULL,
	ReactName	TEXT NOT NULL,
	Count	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(MessageID,ReactName)
);
COMMIT;
